import Head from "next/head";

import Nav from "@/components/Nav";
import Intro from "@/components/Intro";
import TechStack from "@/components/technologoies";
import ProjectsSection from "@/components/projects";
import Footer from "@/components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Swapnil&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../public/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <Nav />
          <Intro />
          <TechStack />
          <ProjectsSection />
          <Footer />
        </section>
      </main>
    </div>
  );
}
