import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";

import Image from "next/image";
import devTiger from "../../public/dev-tiger-wave.png";
import design from "../../public/design.png";
import code from "../../public/code.png";
import consulting from "../../public/consulting.png";

/* https://www.youtube.com/watch?v=k-Pi5ZMxHWY&t=2569s */

export default function Home() {
  return (
    <>
      <Head>
        <title>Swapnil&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../public/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">DevelopedByTiger ✨</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-cyan-500 hover:text-black text-white px-4 py-2 rounded-md ml-8"
                  href="https://www.linkedin.com/in/now-tiger"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Swapnil Narwade
            </h2>
            <h3 className="text-2xl py-2">Student & Developer</h3>
            <p className="text-md py-2 text-gray-800 leading-8">
              Freelancer providing services for programming and data science
              project needs. Join me down below, and lets get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-2">
            <AiFillTwitterCircle className="text-blue-500" />
            <AiFillLinkedin className="text-blue-700" />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto w-96 h-96 mt-20">
            <Image
              src={devTiger}
              alt="TigerDev"
              //layout="fill"
              objectFit="cover"
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-1 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance developer,
              I&apos;ve done remote work for{" "}
              <span className="text-emerald-600">agencies</span>, consulted for{" "}
              <span className="text-emerald-600">startups</span> and
              collaborated with talented people to create digital products for
              both businesses and consumer use.
            </p>
            <p className="text-md py-1 leading-8 text-gray-800">
              I offer wide range services including programming and teaching.
            </p>
          </div>
          <div>
            <div>
              <Image src={design} alt="design" width={100} height={100} />
              {/*You've to complete from here - https://www.youtube.com/watch?v=k-Pi5ZMxHWY&t=2569s
               * >> start @ 34:35
               */}
            </div>
            <div>
              <Image src={code} alt="code" width={100} height={100} />
            </div>
            <div>
              <Image
                src={consulting}
                alt="consulting"
                width={100}
                height={100}
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
